(()=>{"use strict";const $=x=>document.getElementById(x),A=$("arena"),S=$("stage"),R=$("route");let W=20,H=40,z=.72,start={x:2,y:37},finish={x:18,y:3},rot=false,hide=false,nums=true,showRoute=true,draw=false,path=[],showDistanceLines=true,multiMode=false,multiSel=new Set();let O=[{x:7,y:8,type:"rail",angle:0,height:80},{x:15,y:13,type:"oxer",angle:18,height:90},{x:6,y:23,type:"rail",angle:0,height:70},{x:14,y:27,type:"groundpole",angle:0},{x:10,y:34,type:"rail",angle:18,height:100}].map(o=>({...o,edge:false}));let sel={kind:"obstacle",index:0};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),name=t=>t==="rail"?"Räcke":t==="oxer"?"Oxer":t==="groundpole"?"Markbom":"Kon",pnt=e=>{let r=A.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*W,0,W),y:clamp((e.clientY-r.top)/r.height*H,0,H)}};function pos(e,o){e.style.left=o.x/W*100+"%";e.style.top=o.y/H*100+"%"}function drag(e,o,s){let on=false,id,sa,sp;e.onpointerdown=v=>{if(draw)return;v.preventDefault();v.stopPropagation();on=true;id=v.pointerId;sel=s;
  if(multiMode&&s.kind==="obstacle"){
    if(multiSel.has(s.index))multiSel.delete(s.index);else multiSel.add(s.index);
  }else if(!multiMode){multiSel.clear()}
  try{e.setPointerCapture(id)}catch(_){}if(rot&&s.kind==="obstacle"){let r=A.getBoundingClientRect(),cx=r.left+o.x/W*r.width,cy=r.top+o.y/H*r.height;sp=Math.atan2(v.clientY-cy,v.clientX-cx)*180/Math.PI;sa=o.angle||0}renderSel()};e.onpointermove=v=>{if(!on||v.pointerId!==id)return;if(rot&&s.kind==="obstacle"){let r=A.getBoundingClientRect(),cx=r.left+o.x/W*r.width,cy=r.top+o.y/H*r.height;o.angle=(sa+Math.atan2(v.clientY-cy,v.clientX-cx)*180/Math.PI-sp+360)%360;e.style.setProperty("--a",o.angle+"deg")}else{Object.assign(o,pnt(v));pos(e,o);measures()}};e.onpointerup=e.onpointercancel=()=>on=false}function distanceLine(a,b){
 if(!showDistanceLines||!a||!b||a.type==="cone"||b.type==="cone")return;
 let dx=(b.x-a.x)/W*A.clientWidth,dy=(b.y-a.y)/H*A.clientHeight;
 let e=document.createElement("span");e.className="distance-line";
 e.style.left=a.x/W*100+"%";e.style.top=a.y/H*100+"%";
 e.style.width=Math.hypot(dx,dy)+"px";e.style.transform="rotate("+Math.atan2(dy,dx)+"rad)";
 A.append(e)
}function measure(a,b){if(!a||!b||a.type==="cone"||b.type==="cone")return;let e=document.createElement("span");e.className="measure";e.textContent=d(a,b).toFixed(1)+" m";e.style.left=(a.x+b.x)/2/W*100+"%";e.style.top=(a.y+b.y)/2/H*100+"%";A.append(e)}function measures(){A.querySelectorAll(".measure,.distance-line").forEach(e=>e.remove());if(hide)return;let m=O.filter(o=>o.type!=="cone");if(m.length){distanceLine(start,m[0]);measure(start,m[0]);for(let i=0;i<m.length-1;i++){distanceLine(m[i],m[i+1]);measure(m[i],m[i+1])}distanceLine(m.at(-1),finish);measure(m.at(-1),finish)}let chosen=multiMode&&multiSel.size?[...multiSel].map(i=>O[i]).filter(Boolean):(sel.kind==="obstacle"?[O[sel.index]]:[]);
chosen.filter(o=>o&&o.edge).forEach(o=>[[o.x/2,o.y,o.x],[(o.x+W)/2,o.y,W-o.x],[o.x,o.y/2,o.y],[o.x,(o.y+H)/2,H-o.y]].forEach(q=>{let e=document.createElement("span");e.className="measure edge";e.textContent=q[2].toFixed(1)+" m";e.style.left=q[0]/W*100+"%";e.style.top=q[1]/H*100+"%";A.append(e)}))}function route(){R.innerHTML="";if(!showRoute||path.length<2)return;let ns="http://www.w3.org/2000/svg",p=document.createElementNS(ns,"polyline");p.setAttribute("class","ridepath");p.setAttribute("points",path.map(o=>o.x/W*1000+","+o.y/H*2000).join(" "));R.append(p);for(let i=8;i<path.length;i+=12){let a=path[i-1],b=path[i],x=b.x/W*1000,y=b.y/H*2000,ang=Math.atan2((b.y-a.y)/H*2000,(b.x-a.x)/W*1000)*180/Math.PI,e=document.createElementNS(ns,"path");e.setAttribute("class","arrow");e.setAttribute("d","M -15 -10 L 0 0 L -15 10");e.setAttribute("transform",`translate(${x} ${y}) rotate(${ang})`);R.append(e)}}function renderSel(){A.querySelectorAll(".selected").forEach(e=>e.classList.remove("selected"));if(sel.kind==="obstacle")A.querySelectorAll(".obstacle")[sel.index]?.classList.add("selected");
A.querySelectorAll(".obstacle").forEach((e,i)=>e.classList.toggle("multi-selected",multiSel.has(i)));else A.querySelector("."+sel.kind)?.classList.add("selected");let o=sel.kind==="obstacle"?O[sel.index]:null;$("edgeMeasures").disabled=!o;let chosen=multiMode&&multiSel.size?[...multiSel].map(i=>O[i]).filter(Boolean):(o?[o]:[]);
$("edgeMeasures").classList.toggle("active",!!(chosen.length&&chosen.every(x=>x.edge)));$("rotate").disabled=!o;$("rotate").classList.toggle("active",rot);$("selectedTitle").textContent=o?name(o.type):sel.kind==="start"?"Start":"Mål";$("heightField").style.display=o&&(o.type==="rail"||o.type==="oxer")?"flex":"none";$("oxerWidthField").style.display=o?.type==="oxer"?"flex":"none";if(o?.height)$("heightSelect").value=o.height;measures()}function render(){A.querySelectorAll(".obstacle,.point,.measure").forEach(e=>e.remove());let w=560*z;A.style.width=S.style.width=w+"px";A.style.height=S.style.height=w*H/W+"px";$("widthLabel").textContent=W+" m";$("lengthLabel").textContent=H+" m";$("zoomText").textContent=Math.round(z*100)+"%";let n=0;O.forEach((o,i)=>{let e=document.createElement("div");e.className="obstacle "+o.type;e.style.setProperty("--a",(o.angle||0)+"deg");if(o.type!=="cone")e.style.width=3/W*100+"%";let h="";if(o.type!=="cone"&&nums)h=`<span class=num>${++n}</span>`;else if(o.type!=="cone")n++;if(["rail","oxer"].includes(o.type))h+=`<span class=height-label>${o.height} cm</span>`;e.innerHTML=h;pos(e,o);A.append(e);drag(e,o,{kind:"obstacle",index:i})});[["start","START",start],["finish","MÅL",finish]].forEach(v=>{let e=document.createElement("div");e.className="point "+v[0];e.textContent=v[1];pos(e,v[2]);A.append(e);drag(e,v[2],{kind:v[0]})});route();renderSel()}function add(t){let o={x:W/2,y:H/2,type:t,angle:0,edge:false};if(["rail","oxer"].includes(t))o.height=80;O.push(o);sel={kind:"obstacle",index:O.length-1};render()}document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add));for(let h=30;h<=150;h+=10)$("heightSelect").insertAdjacentHTML("beforeend",`<option>${h}</option>`);$("heightSelect").onchange=e=>{O[sel.index].height=+e.target.value;render()};$("zoomIn").onclick=()=>{z=clamp(z+.15,.55,2.2);render()};$("zoomOut").onclick=()=>{z=clamp(z-.15,.55,2.2);render()};$("rotate").onclick=()=>{rot=!rot;draw=false;renderSel()};$("edgeMeasures").onclick=()=>{
 let chosen=multiMode&&multiSel.size?[...multiSel].map(i=>O[i]).filter(Boolean):(sel.kind==="obstacle"?[O[sel.index]]:[]);
 if(!chosen.length)return;let turnOn=!chosen.every(o=>o.edge);chosen.forEach(o=>o.edge=turnOn);renderSel()
};
$("toggleDistanceLines").onclick=()=>{showDistanceLines=!showDistanceLines;$("toggleDistanceLines").classList.toggle("active",showDistanceLines);measures()};
$("multiSelect").onclick=()=>{multiMode=!multiMode;if(!multiMode)multiSel.clear();$("multiSelect").classList.toggle("active",multiMode);renderSel()};$("hideMeasures").onclick=()=>{hide=!hide;$("hideMeasures").classList.toggle("active",!hide);measures()};$("toggleNumbers").onclick=()=>{nums=!nums;$("toggleNumbers").classList.toggle("active",nums);render()};$("toggleRoute").onclick=()=>{showRoute=!showRoute;$("toggleRoute").classList.toggle("active",showRoute);route()};$("drawRoute").onclick=()=>{draw=!draw;rot=false;showRoute=true;$("drawRoute").classList.toggle("active",draw)};$("clearRoute").onclick=()=>{path=[];route()};$("duplicate").onclick=()=>{if(sel.kind==="obstacle"){let i=sel.index,o={...O[i],x:clamp(O[i].x+2,0,W),y:clamp(O[i].y+2,0,H),edge:false};O.splice(i+1,0,o);sel.index=i+1;render()}};$("remove").onclick=()=>{if(sel.kind==="obstacle"){O.splice(sel.index,1);multiSel.clear();sel=O.length?{kind:"obstacle",index:Math.min(sel.index,O.length-1)}:{kind:"start"};render()}};$("arenaSize").onchange=e=>{[W,H]=e.target.value.split(",").map(Number);render()};let drawing=false,id;A.addEventListener("pointerdown",e=>{if(!draw||e.target.closest(".obstacle,.point"))return;e.preventDefault();drawing=true;id=e.pointerId;path=[pnt(e)];try{A.setPointerCapture(id)}catch(_){}route()});A.addEventListener("pointermove",e=>{if(!drawing||e.pointerId!==id)return;let p=pnt(e),l=path.at(-1);if(d(l,p)>.18){path.push(p);route()}});A.addEventListener("pointerup",()=>drawing=false);A.addEventListener("pointercancel",()=>drawing=false);
let resizeTimer;window.addEventListener("resize",()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,120)});
render()})();